import Head from "next/head";
import Link from "next/link";
import { questionData } from "../pages/dataQuestion";

export default function Layout({ children }) {
  return <div>
    <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />

    </Head>
    <nav className="navbar navbar-expand-lg navbar-light bg-light">
  <div className="container-fluid">
    <Link href="/"><a className="navbar-brand">Home</a></Link>
    <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span className="navbar-toggler-icon"></span>
    </button>
    <div className="collapse navbar-collapse" id="navbarSupportedContent">
      <ul className="navbar-nav me-auto mb-2 mb-lg-0">
        <li className="nav-item dropdown">
          <Link href="#">
            <a className="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Mental Card
            </a>
          </Link>
              <ul className="dropdown-menu" aria-labelledby="navbarDropdown">
                {questionData.map((element) => {
                  return (<li key={element.id}><Link href={`/mentalCard/${element.id}`}><a className="dropdown-item">Card{element.id}</a></Link></li>);
                })}
          </ul>
        </li>
        <li className="nav-item dropdown">
          <Link href="#">
            <a className="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Mental Card Input
            </a>
          </Link>
              <ul className="dropdown-menu" aria-labelledby="navbarDropdown">
                {questionData.map((element) => {
                  return (<li key={element.id}><Link href={`/mentalInput/${element.id}`}><a className="dropdown-item">Card{element.id}</a></Link></li>);
                })}
          </ul>
        </li>
        <li className="nav-item dropdown">
          <Link href="#">
            <a className="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Mental Card Choice
            </a>
          </Link>
              <ul className="dropdown-menu" aria-labelledby="navbarDropdown">
                {questionData.map((element) => {
                  return (<li key={element.id}><Link href={`/mentalChoice/${element.id}`}><a className="dropdown-item">Card {element.id}</a></Link></li>);
                })}
          </ul>
        </li>
    </ul>
    </div>
  </div>
</nav>
  {children}

  </div>
}
